= Configuración Multiusuario
:revdate: 2025-04-30
:page-revdate: {revdate}

{product_name} utiliza Kubernetes RBAC siempre que sea posible.

Una adición al RBAC es el recurso xref:explanations/namespaces.adoc#_restricting_gitrepos[`+GitRepoRestriction+`] que puede utilizarse para controlar los recursos de GitRepo en un espacio de nombres.

Una configuración de flota multiusuario tiene este aspecto:

* los inquilinos no comparten espacios de nombres, cada inquilino tiene uno o más espacios de nombres en el clúster ascendente, donde pueden crear recursos GitRepo
* los inquilinos no pueden desplegar recursos en todo el clúster y están limitados a un conjunto de espacios de nombres en los clústeres posteriores
* están en un espacio de nombres separado

image::FleetSharedClusters.svg[Clusters compartidos]

[CAUTION]
.información importante
====

El aislamiento de los inquilinos no es completo y depende de que Kubernetes RBAC esté configurado correctamente. Sin la configuración manual de un operador, los inquilinos pueden desplegar recursos en todo el clúster. Incluso con las restricciones disponibles en {product_name}, los usuarios sólo están restringidos a espacios de nombres, pero los espacios de nombres no proporcionan mucho aislamiento por sí solos. Por ejemplo, pueden seguir consumiendo tantos recursos como quieran.

Sin embargo, las restricciones existentes en {product_name} permiten a los usuarios compartir clusters y desplegar recursos sin conflictos.
====


== Ejemplo {product_name} Standalone

Esto crearía un usuario 'fleetuser', que sólo puede gestionar recursos GitRepo en el espacio de nombres 'project1'.

[,bash]
----
 kubectl create serviceaccount fleetuser
 kubectl create namespace project1
 kubectl create -n project1 role fleetuser --verb=get --verb=list --verb=create --verb=delete --resource=gitrepos.fleet.cattle.io
 kubectl create -n project1 rolebinding fleetuser --serviceaccount=default:fleetuser --role=fleetuser
----

Si queremos dar acceso a varios espacios de nombres, podemos utilizar un único rol de clúster con dos vinculaciones de rol:

[,bash]
----
 kubectl create clusterrole fleetuser --verb=get --verb=list --verb=create --verb=delete --resource=gitrepos.fleet.cattle.io
 kubectl create -n project1 rolebinding fleetuser --serviceaccount=default:fleetuser --clusterrole=fleetuser
 kubectl create -n project2 rolebinding fleetuser --serviceaccount=default:fleetuser --clusterrole=fleetuser
----

Esto asegura que los tenants no puedan interferir con los recursos GitRepo de otros tenants, ya que no tienen acceso a sus namespaces.

== Ejemplo {product_name} en Rancher

Cuando se crea un nuevo espacio de trabajo de flota, se genera automáticamente un espacio de nombres correspondiente con un nombre idéntico dentro del clúster local de Rancher.
Para que un usuario pueda ver y desplegar recursos de flota en un espacio de trabajo específico, necesita al menos los siguientes permisos:

* listar/obtener el recurso `+fleetworkspace+` cluster-wide en el cluster local
* Permisos para crear recursos de flota (como `+bundles+`, `+gitrepos+`, ...) en el espacio de nombres de respaldo para el espacio de trabajo en el clúster local.

Concedamos permisos para desplegar recursos de flota en los espacios de trabajo de flota `+project1+` y `+project2+`:

ifeval::["{product}" == "fleet"]
* Para crear los espacios de trabajo de las flotas `+project1+` y `+project2+`, puede hacerlo en la https://ranchermanager.docs.rancher.com/integrations-in-rancher/fleet/overview#accessing-fleet-in-the-rancher-ui[interfaz de usuario de Rancher] o utilizar los siguientes recursos YAML:
endif::[]

ifeval::["{product}" == "continuous-delivery"]

* Para crear los espacios de trabajo de las flotas `+project1+` y `+project2+`, puede hacerlo en la https://documentation.suse.com/cloudnative/rancher-manager/latest/en/integrations/fleet/overview.html#_accessing_suse_rancher_prime_continuous_delivery_in_the_rancher_ui[interfaz de usuario de Rancher] o utilizar los siguientes recursos YAML:

[,yaml]
----
apiVersion: management.cattle.io/v3
kind: FleetWorkspace
metadata:
  name: project1
----

[,yaml]
----
apiVersion: management.cattle.io/v3
kind: FleetWorkspace
metadata:
  name: project2
----

* Cree un `+GlobalRole+` que conceda permiso para desplegar recursos de flota en los espacios de trabajo de flota `+project1+` y `+project2+`:

[,yaml]
----
apiVersion: management.cattle.io/v3
kind: GlobalRole
metadata:
  name: fleet-projects1and2
namespacedRules:
  project1:
    - apiGroups:
        - fleet.cattle.io
      resources:
        - gitrepos
        - bundles
        - clusterregistrationtokens
        - gitreporestrictions
        - clusters
        - clustergroups
      verbs:
        - '*'
  project2:
    - apiGroups:
        - fleet.cattle.io
      resources:
        - gitrepos
        - bundles
        - clusterregistrationtokens
        - gitreporestrictions
        - clusters
        - clustergroups
      verbs:
        - '*'
rules:
  - apiGroups:
      - management.cattle.io
    resourceNames:
      - project1
      - project2
    resources:
      - fleetworkspaces
    verbs:
      - '*'
----

ifeval::["{product}" == "fleet"]
Asigne `+GlobalRole+` a usuarios o grupos; encontrará más información en https://ranchermanager.docs.rancher.com/how-to-guides/new-user-guides/authentication-permissions-and-global-configuration/manage-role-based-access-control-rbac/global-permissions#configuring-global-permissions-for-individual-users[la documentación de].
endif::[]

ifeval::["{product}" == "continuous-delivery"]

Asigne `+GlobalRole+` a usuarios o grupos; encontrará más información en https://documentation.suse.com/cloudnative/rancher-manager/v2.12/en/rancher-admin/users/authn-and-authz/manage-role-based-access-control-rbac/global-permissions.html#_configuring_global_permissions_for_individual_users[la documentación de].
endif::[]

El usuario ahora tiene acceso a la pestaña `+Continuous Delivery+` en Rancher y puede desplegar recursos tanto en el espacio de trabajo `+project1+` como en `+project2+`.

Para tener un entorno bien organizado, cada espacio de trabajo debe tener su propio `+GlobalRole+` relacionado para ayudar con la separación de tareas y el aislamiento que requiere el cliente. De este modo, cada usuario puede ser asignado a uno o varios `+GlobalRoles+`, en función de las necesidades.

== Permitir el acceso a los clusters

Esto supone que todos los GitRepos creados por 'fleetuser' tienen la etiqueta `+team: one+`. Se pueden utilizar diferentes etiquetas para seleccionar diferentes espacios de nombres de clúster.

En cada uno de los espacios de nombres de usuario, como administrador, cree un espacio de nombres xref:explanations/namespaces.adoc#_cross_namespace_deployments[`+BundleNamespaceMapping+`].

[,yaml]
....
kind: BundleNamespaceMapping
apiVersion: fleet.cattle.io/v1alpha1
metadata:
  name: mapping
  namespace: project1

# Bundles to match by label.
# The labels are defined in the fleet.yaml # labels field or from the
# GitRepo metadata.labels field
bundleSelector:
  matchLabels:
    team: one
    # or target one repo
    #fleet.cattle.io/repo-name: simpleapp

# Namespaces, containing clusters, to match by label
namespaceSelector:
  matchLabels:
    kubernetes.io/metadata.name: fleet-default
    # the label is on the namespace
    #workspace: prod
....

La xref:how-tos-for-users/gitrepo-targets.adoc[sección`+target+` ] del recurso GitRepo puede utilizarse para desplegar sólo en un subconjunto de los clusters coincidentes.

== Restricción del acceso a los clusters descendentes

Los administradores pueden restringir aún más los inquilinos creando un `+GitRepoRestriction+` en cada uno de sus espacios de nombres.

[,yaml]
....
kind: GitRepoRestriction
apiVersion: fleet.cattle.io/v1alpha1
metadata:
  name: restriction
  namespace: project1

allowedTargetNamespaces:
  - project1simpleapp
....

Esto denegará la creación de recursos en todo el clúster, que pueden interferir con otros inquilinos y limitar el despliegue al espacio de nombres 'project1simpleapp'.

== Un ejemplo de recurso GitRepo

Un recurso GitRepo creado por un tenant, sin acceso de administrador podría tener este aspecto:

[,yaml]
....
kind: GitRepo
apiVersion: fleet.cattle.io/v1alpha1
metadata:
  name: simpleapp
  namespace: project1
  labels:
    team: one

spec:
  repo: https://github.com/rancher/fleet-examples
  paths:
  - bundle-diffs

  targetNamespace: project1simpleapp

  # do not match the upstream/local cluster, won't work
  targets:
  - name: dev
    clusterSelector:
      matchLabels:
        env: dev
....

Incluye la etiqueta `+team: one+` y la dirección `+targetNamespace+`.

Junto con el anterior `+BundleNamespaceMapping+` se dirigiría a todos los clusters con una etiqueta `+env: dev+` en el espacio de nombres 'fleet-default'.

[NOTE]
====

`+BundleNamespaceMappings+` no funcionan con clusters locales, así que asegúrate de no apuntar a ellos.
====

