= マルチユーザー設定
:revdate: 2025-04-30
:page-revdate: {revdate}

{product_name} は可能な限りKubernetes RBACを使用する。

RBAC の上に追加されたもののひとつが xref:explanations/namespaces.adoc#_restricting_gitrepos[`+GitRepoRestriction+`]リソースを使うことで、名前空間内の GitRepo リソースを制御することができます。

マルチユーザーフリートのセットアップは次のようになる：

* テナントは名前空間を共有しません。各テナントは上流のクラスターにひとつ以上の名前空間を持ち、そこで GitRepo リソースを作成します。
* テナントはクラスタ全体のリソースをデプロイできず、ダウンストリームクラスタ上の一連のネームスペースに制限される。
* クラスタは別の名前空間にある。

image::FleetSharedClusters.svg[共有クラスター]

[CAUTION]
.重要情報
====

テナントの分離は完全ではなく、KubernetesのRBACが正しく設定されているかどうかに依存する。オペレータが手動でセットアップしなくても、テナントはクラスタ全体のリソースをデプロイできる。利用可能な{product_name} 制限があっても、ユーザーはネームスペースに制限されるだけで、ネームスペースはそれだけではあまり隔離されません。例えば、彼らは好きなだけ資源を消費することができる。

しかし、既存の{product_name} の制限により、ユーザーはクラスタを共有し、競合することなくリソースを配置することができる。
====


== 例{product_name} スタンドアロン

これは、'project1' 名前空間の GitRepo リソースだけを管理できるユーザー 'fleetuser' を作成することになります。

[,bash]
----
 kubectl create serviceaccount fleetuser
 kubectl create namespace project1
 kubectl create -n project1 role fleetuser --verb=get --verb=list --verb=create --verb=delete --resource=gitrepos.fleet.cattle.io
 kubectl create -n project1 rolebinding fleetuser --serviceaccount=default:fleetuser --role=fleetuser
----

複数のネームスペースにアクセスさせたい場合は、2つのロール・バインディングを持つ1つのクラスタ・ロールを使用できます：

[,bash]
----
 kubectl create clusterrole fleetuser --verb=get --verb=list --verb=create --verb=delete --resource=gitrepos.fleet.cattle.io
 kubectl create -n project1 rolebinding fleetuser --serviceaccount=default:fleetuser --clusterrole=fleetuser
 kubectl create -n project2 rolebinding fleetuser --serviceaccount=default:fleetuser --clusterrole=fleetuser
----

これは、テナントが他のテナントのGitRepoリソースに干渉できないようにするものです。テナントは名前空間にアクセスできないからです。

== ランチャーの例{product_name} 

新しいフリートワークスペースが作成されると、Rancherローカルクラスタ内に同じ名前の対応する名前空間が自動的に生成される。
ユーザーが特定のワークスペースにフリートリソースを表示および配置するには、少なくとも以下のパーミッションが必要です：

* `+fleetworkspace+` クラスタ全体のリソースをローカルクラスタにリスト/取得する。
* ローカル・クラスター内のワークスペースのバッキング・ネームスペースにフリート・リソース（`+bundles+` 、`+gitrepos+` 、... など）を作成する権限。

`+project1+` と`+project2+` のフリートワークスペー スに、フリートリソースをデプロイする権限を与えよう：

ifeval::["{product}" == "fleet"]
* `+project1+` と`+project2+` フリート・ワークスペースを作成するには、https://ranchermanager.docs.rancher.com/integrations-in-rancher/fleet/overview#accessing-fleet-in-the-rancher-ui[]Rancherで行うか、以下の YAML リソースを使用する：
endif::[]

ifeval::["{product}" == "continuous-delivery"]

* `+project1+` と`+project2+` フリート・ワークスペースを作成するには、https://documentation.suse.com/cloudnative/rancher-manager/latest/en/integrations/fleet/overview.html#_accessing_suse_rancher_prime_continuous_delivery_in_the_rancher_ui[]Rancherで行うか、以下の YAML リソースを使用する：

[,yaml]
----
apiVersion: management.cattle.io/v3
kind: FleetWorkspace
metadata:
  name: project1
----

[,yaml]
----
apiVersion: management.cattle.io/v3
kind: FleetWorkspace
metadata:
  name: project2
----

* `+project1+` 、`+project2+` のフリートワークスペースにフリートリソースを配置する権限を与える`+GlobalRole+` を作成します：

[,yaml]
----
apiVersion: management.cattle.io/v3
kind: GlobalRole
metadata:
  name: fleet-projects1and2
namespacedRules:
  project1:
    - apiGroups:
        - fleet.cattle.io
      resources:
        - gitrepos
        - bundles
        - clusterregistrationtokens
        - gitreporestrictions
        - clusters
        - clustergroups
      verbs:
        - '*'
  project2:
    - apiGroups:
        - fleet.cattle.io
      resources:
        - gitrepos
        - bundles
        - clusterregistrationtokens
        - gitreporestrictions
        - clusters
        - clustergroups
      verbs:
        - '*'
rules:
  - apiGroups:
      - management.cattle.io
    resourceNames:
      - project1
      - project2
    resources:
      - fleetworkspaces
    verbs:
      - '*'
----

ifeval::["{product}" == "fleet"]
`+GlobalRole+` をユーザーまたはグループに割り当てます。詳細はhttps://ranchermanager.docs.rancher.com/how-to-guides/new-user-guides/authentication-permissions-and-global-configuration/manage-role-based-access-control-rbac/global-permissions#configuring-global-permissions-for-individual-users[ドキュメントを] Rancher の参照してください。
endif::[]

ifeval::["{product}" == "continuous-delivery"]

`+GlobalRole+` をユーザーまたはグループに割り当てます。詳細はhttps://documentation.suse.com/cloudnative/rancher-manager/v2.12/en/rancher-admin/users/authn-and-authz/manage-role-based-access-control-rbac/global-permissions.html#_configuring_global_permissions_for_individual_users[ドキュメントを] Rancher の参照してください。
endif::[]

このユーザーは、Rancherの`+Continuous Delivery+` タブにアクセスできるようになり、`+project1+` と`+project2+` の両方のワークスペースにリソースをデプロイできるようになった。

整理整頓された環境を作るために、各ワークスペースにはそれぞれ関連する`+GlobalRole+` 。このようにして、各ユーザーはニーズに応じて、1つまたは複数の`+GlobalRoles+` に割り当てることができる。

== クラスタへのアクセスを許可する

これは、'fleetuser'が作成したすべてのGitReposが`+team: one+` 。異なるクラスタ名前空間を選択するために、異なるラベルを使用することもできる。

各ユーザーのネームスペースに、管理者として xref:explanations/namespaces.adoc#_cross_namespace_deployments[`+BundleNamespaceMapping+`].

[,yaml]
....
kind: BundleNamespaceMapping
apiVersion: fleet.cattle.io/v1alpha1
metadata:
  name: mapping
  namespace: project1

# Bundles to match by label.
# The labels are defined in the fleet.yaml # labels field or from the
# GitRepo metadata.labels field
bundleSelector:
  matchLabels:
    team: one
    # or target one repo
    #fleet.cattle.io/repo-name: simpleapp

# Namespaces, containing clusters, to match by label
namespaceSelector:
  matchLabels:
    kubernetes.io/metadata.name: fleet-default
    # the label is on the namespace
    #workspace: prod
....

GitRepoリソースのxref:how-tos-for-users/gitrepo-targets.adoc[`+target+` セクションを]使うと、マッチしたクラスタのサブセットだけにデプロイすることができます。

== 下流クラスターへのアクセス制限

管理者は、各ネームスペースに`+GitRepoRestriction+` を作成することで、テナントをさらに制限することができます。

[,yaml]
....
kind: GitRepoRestriction
apiVersion: fleet.cattle.io/v1alpha1
metadata:
  name: restriction
  namespace: project1

allowedTargetNamespaces:
  - project1simpleapp
....

これにより、他のテナントと干渉する可能性のあるクラスタ全体のリソースの作成が拒否され、デプロイが「project1simpleapp」名前空間に制限されます。

== GitRepo リソースの例

管理者権限のないテナントが作成した GitRepo リソースは次のようになります：

[,yaml]
....
kind: GitRepo
apiVersion: fleet.cattle.io/v1alpha1
metadata:
  name: simpleapp
  namespace: project1
  labels:
    team: one

spec:
  repo: https://github.com/rancher/fleet-examples
  paths:
  - bundle-diffs

  targetNamespace: project1simpleapp

  # do not match the upstream/local cluster, won't work
  targets:
  - name: dev
    clusterSelector:
      matchLabels:
        env: dev
....

これには`+team: one+` のラベルと、必要な`+targetNamespace+` が含まれる。

以前の`+BundleNamespaceMapping+` 、'fleet-default'ネームスペースの`+env: dev+` ラベルを持つすべてのクラスタを対象とする。

[NOTE]
====

`+BundleNamespaceMappings+` ローカル・クラスターでは動作しないので、ターゲットにしないこと。
====

