= Personas-chave e suas funções
:revdate: 2025-05-30
:page-revdate: {revdate}

[cols="1,2,2", options="header"]
|===
|Persona |Responsabilidades |Principais benefícios

|Engenheiros de plataforma
a|* Configure e gerencie a instalação do {product_name} em clusters.
* Defina e aplique implementações de políticas e aplicativos em vários clusters.
* Gerencie as configurações do GitRepo e do `fleet.yaml`.
* Realizar atualizações e reversões em todo o cluster.
a|* Controle centralizado entre clusters.
* Melhoria da padronização e da conformidade.

|Desenvolvedores de aplicativos
a|* Estruture os gráficos ou manifestos do aplicativo Helm no Git.
* Defina alvos e ambientes de implantação em `fleet.yaml`.
* Monitore o status da implementação via UI ou CLI.
a|* Fluxos de trabalho baseados em GitOps.
* Implementações mais rápidas, automatizadas e consistentes em todos os ambientes.

|Administradores de segurança
a|* Definir e aplicar políticas de segurança como código.
* Implantar ferramentas e configurações de segurança.
* Audite e gerencie a postura de segurança em todos os clusters.
a|* Redução dos riscos e gerenciamento centralizado da conformidade.
* Configuração de segurança automatizada e consistente.
|===
