= v0.13.0
:revdate: 2025-07-23
:page-revdate: {revdate}
:page-date: 2025-07-23 15:09:14 +0000 UTC

*Publicado el 2025-07-23 15:09:14 +0000 UTC por `+github-actions[bot]+`.*

== Descripción

== Cambios notables

* HelmOps y el almacenamiento OCI son ahora totalmente compatibles y ya no son experimentales.
* Mejora de la trazabilidad de las imágenes construidas.
* Actualizaciones del estado de los recursos más precisas y ligeras.

== Adiciones

* {product_name} admite un nuevo método de escaneado de paquetes dirigido por el usuario para una mayor flexibilidad. El método de escaneado anterior sigue siendo compatible. Ver xref:explanations/gitrepo-content.adoc#_alternative_scan_explicitly_defined_by_the_user[documentación],aportada por @0xavi0, PR https://github.com/rancher/fleet/pull/3480[] #3480.
* Cuando se utiliza SSH para apuntar a un repositorio Git, {product_name} comprueba las claves de host por defecto, rechazando intentos de conexión a hosts desconocidos xref:/how-tos-for-users/gitrepo-add.adoc[Known hosts] by https://github.com/weyfonk[PR#3523] @weyfonk in link:https://github.com/rancher/fleet/issues/3523[].
* Los recuentos de réplicas son ahora configurables tanto para los controladores como para los agentes. Consulte xref:how-tos-for-operators/installation.adoc#_controller_and_agent_replicas[la documentación].
  (Contribución de @p-se, PR https://github.com/rancher/fleet/pull/3457[] #3457)
* {product_name} ahora puede utilizar un secreto webhook independiente para cada GitRepo. Consulte xref:how-tos-for-users/webhook.adoc#option-2-configure-secret[la documentación].
  (Contribución de @0xavi0, PR https://github.com/rancher/fleet/pull/3490[] #3490)
* {product_name} ahora admiten etiquetas y anotaciones adicionales, que se propagan a las implantaciones de controladores.
  (Contribución de @0xavi0 y @p-se, PRs https://github.com/rancher/fleet/pull/3531[] #3531 y https://github.com/rancher/fleet/pull/3664[] #3664)
* La elección del líder de los agentes es ahora configurable. Consulte el https://github.com/rancher/fleet/blob/main/charts/fleet/values.yaml#L135-L138[ejemplo].
  (Contribución de @p-se, PR https://github.com/rancher/fleet/pull/3463[] #3463)
* Se ha eliminado la antigua migración de cuentas de servicio. (Contribución de @weyfonk, PR https://github.com/rancher/fleet/pull/3601[] #3601)
* {product_name} ya no calcula las claves de recursos en los estados de los paquetes. (Contribución de @manno, PR https://github.com/rancher/fleet/pull/3681[] #3681)
* {product_name} añade nuevas métricas de GitJob. Consulte xref:how-tos-for-users/observability.adoc#_metrics[la documentación].
  (Contribución de @p-se, PR https://github.com/rancher/fleet/pull/3649[] #3649)
* Ahora los agentes pueden omitir grupos utilizando una etiqueta. (Contribución de @manno, PR https://github.com/rancher/fleet/pull/3744[] #3744)

=== HelmOps

HelmOps ya no es experimental.`+HelmOp+` resources (renamed from `+HelmApp+`) now support:

* Sondeo de repositorios Helm
* Restricciones semánticas de versionado (véase https://github.com/rancher/fleet/issues/3862[este problema conocido] para los gráficos OCI)
* Prevención de colisiones de nombres de paquetes entre paquetes GitOps y HelmOps
* Instalación de cartas Helm en modo TLS estricto

Las métricas y el estado de los clústeres incluyen ahora datos de HelmOps. Para más información, consulte xref:how-tos-for-users/helm-ops.adoc[la documentación de{product_name} ].

=== Almacenamiento OCI

El almacenamiento OCI ha dejado de ser experimental y está activado por defecto, aunque los paquetes no lo utilizarán por defecto. Aún puede desactivarse configurando `+OCI_STORAGE=false+` en `+extraEnv+` al instalar {product_name}.

También es compatible con la recogida de basuras al mejor esfuerzo, así como con la mejora de la trazabilidad de los secretos utilizados en el almacenamiento OCI. Esto incluye el etiquetado de los secretos que {product_name} clona a los clústeres posteriores y la generación de un evento si la eliminación de un artefacto OCI produce un error.

Consulte xref:how-tos-for-users/oci-storage.adoc[la documentación de{product_name} ] para más detalles.

=== Mejoras de la trazabilidad

{product_name} atestigua ahora la procedencia de los manifiestos Docker.
(Parche de @thardeck, PR https://github.com/rancher/fleet/pull/3846[] #3846)

== Corrección de errores

Las actualizaciones de estado y la gestión del ciclo de vida han recibido importantes mejoras:

* Los estados de GitRepo son ahora más estables cuando varios paquetes no están listos.
  (Contribución de @rbreddy, PR https://github.com/rancher/fleet/pull/3485[] #3485)
* Las actualizaciones de estado de GitRepo están optimizadas.
  (PR https://github.com/rancher/fleet/pull/3604[#3604])
* Las conciliaciones de GitRepo ahora retrasan las actualizaciones para mejorar el rendimiento durante los cambios rápidos.
  (PR https://github.com/rancher/fleet/pull/3558[#3558])
* Se han optimizado las actualizaciones de estado de BundleDeployment.
  (PR https://github.com/rancher/fleet/pull/3887[#3887])
* La detección de deriva ya no actualiza los recursos con diffs vacíos.
  (PR https://github.com/rancher/fleet/pull/3555[#3555])
* {product_name} utiliza las últimas mejoras de detección de preparación del Wrangler.
  (PR https://github.com/rancher/fleet/pull/3853[#3853])
* Los agentes aguas abajo vuelven a informar correctamente de los estados aguas arriba.
  (PR https://github.com/rancher/fleet/pull/3702[#3702])

=== Mejoras del ciclo de vida

* Los filtros de eventos de clúster reducen la creación innecesaria de despliegues de paquetes.
  (PR https://github.com/rancher/fleet/pull/3796[] #3796)
* {product_name} ahora elimina las implantaciones de paquetes obsoletas:
** Ya no es un objetivo.
** GitRepo o Bundle objetivos cambiados.
  (PRs https://github.com/rancher/fleet/pull/3509[] #3509 y https://github.com/rancher/fleet/pull/3438[] #3438)

=== Mejoras en la CLI

* {product_name} CLI ahora proporciona mensajes de error más claros en los trabajos git.
  (PR https://github.com/rancher/fleet/pull/3559[#3559])
* CLI utiliza el cliente `+controller-runtime+`.
  (PR https://github.com/rancher/fleet/pull/3670[#3670])

=== Mejoras en la configuración

* Ahora, las actualizaciones de configuración activan las importaciones de clústeres de forma selectiva:
** Sólo cuando cambian los campos relevantes.
** Sólo cuando existe un `+apiServerURL+` válido.
  (PRs https://github.com/rancher/fleet/pull/3551[] #3551 y https://github.com/rancher/fleet/pull/3837[] #3837)
* Corregido el pánico causado por `+options.Helm+`.
  (PR https://github.com/rancher/fleet/pull/3567[#3567])
* Ya no se permite crear un GitRepo con una URL de repositorio vacía.
  (PR https://github.com/rancher/fleet/pull/3582[#3582])
* Ahora se omiten las opciones de ignorar vacías en BundleDeployments y HelmOps.
  (PR https://github.com/rancher/fleet/pull/3842[] #3842)

=== Otras mejoras

* Errores más informativos para las descargas fallidas de gráficos.
  (PR https://github.com/rancher/fleet/pull/3593[] #3593)
* La autenticación de clave SSH para las descargas de gráficos de Helm vuelve a funcionar.
  (PR https://github.com/rancher/fleet/pull/3670[#3670])
