:doctype: book

= Création d'un déploiement
:revdate: 2025-07-23
:page-revdate: {revdate}

Pour déployer des charges de travail sur des clusters en aval, il faut d'abord créer une archive Git, puis une ressource GitRepo et l'appliquer.

Ce tutoriel utilise le dépôt https://github.com/rancher/fleet-examples[fleet-examples].

[NOTE]
====
Pour plus de détails sur la façon de structurer le dépôt et de configurer le déploiement de chaque paquet, voir xref:explanations/gitrepo-content.adoc[GitRepo Contents.]
Pour plus de détails sur les options disponibles par dépôt Git, voir xref:how-tos-for-users/gitrepo-add.adoc[Ajouter une GitRepo].
====


== Exemples de grappes simples

Tous les exemples déploient du contenu sur des grappes sans personnalisation de chaque grappe. C'est un bon point de départ pour comprendre les bases de la structuration des dépôts Git pour{product_name}.

[tabs,sync-group-id=examples]
====
Tige::
+
Un exemple utilisant Helm. Nous déployons l' https://github.com/rancher/fleet-examples/tree/master/single-cluster/helm[exemple] sur le cluster local.
+
Le référentiel contient un diagramme de barre et un site optionnel `fleet.yaml` pour configurer le déploiement :
+
.fleet.yaml
[source,yaml]
----
namespace: fleet-helm-example

# Custom helm options
helm:
  # The release name to use. If empty a generated release name will be used
  releaseName: guestbook

  # The directory of the chart in the repo.  Also any valid go-getter supported
  # URL can be used there is specify where to download the chart from.
  # If repo below is set this value if the chart name in the repo
  chart: ""

  # An https to a valid Helm repository to download the chart from
  repo: ""

  # Used if repo is set to look up the version of the chart
  version: ""

  # Force recreate resource that can not be updated
  force: false

  # How long for helm to wait for the release to be active. If the value
  # is less that or equal to zero, we will not wait in Helm
  timeoutSeconds: 0

  # Custom values that will be passed as values.yaml to the installation
  values:
    replicas: 2
----

Tableau de bord multiple de la barre::
+
Un https://github.com/rancher/fleet-examples/blob/master/single-cluster/helm-multi-chart[exemple de] à partir d'un seul repo. Cet exemple est similaire au précédent, mais il déploie trois diagrammes de barre à partir des sous-dossiers, chacun étant configuré par sa propre adresse `fleet.yaml`.
+
[source,bash]
----
kubectl apply -n fleet-local -f - <<EOF
kind: GitRepo
apiVersion: fleet.cattle.io/v1alpha1
metadata:
  name: helm
spec:
  repo: https://github.com/rancher/fleet-examples
  paths:
  - single-cluster/helm-multi-chart
EOF
----

Barrer et personnaliser::
+
Exemple d'utilisation de https://github.com/rancher/fleet-examples/blob/master/single-cluster/helm-kustomize[pour modifier une carte Helm d'un tiers] Kustomize. Il déploiera l'exemple d'application de livre d'or Kubernetes sous la forme d'un diagramme Helm téléchargé à partir d'une source tierce et modifiera le diagramme Helm à l'aide de Kustomize. L'application sera déployée dans l'espace de noms fleet-helm-kustomize-example. 
+
[source,bash]
----
kubectl apply -n fleet-local -f - <<EOF
kind: GitRepo
apiVersion: fleet.cattle.io/v1alpha1
metadata:
  name: helm
spec:
  repo: https://github.com/rancher/fleet-examples
  paths:
  - single-cluster/helm-kustomize
EOF
----

Kustomize::
+
Un https://github.com/rancher/fleet-examples/blob/master/single-cluster/kustomize[exemple]. 
+
Notez que le site `fleet.yaml` possède une clé `kustomize:` pour spécifier le chemin d'accès au site `kustomization.yaml` requis :
+
.fleet.yaml
[source,yaml]
----
kustomize:
  # To use a kustomization.yaml different from the one in the root folder
  dir: ""
----
+
[source,bash]
----
kubectl apply -n fleet-local -f - <<EOF
kind: GitRepo
apiVersion: fleet.cattle.io/v1alpha1
metadata:
  name: helm
spec:
  repo: https://github.com/rancher/fleet-examples
  paths:
  - single-cluster/kustomize
EOF
----

Manifestes::
+
Un https://github.com/rancher/fleet-examples/tree/master/single-cluster/manifests[exemple].
+
[source,bash]
----
kubectl apply -n fleet-local -f - <<EOF
kind: GitRepo
apiVersion: fleet.cattle.io/v1alpha1
metadata:
  name: helm
spec:
  repo: https://github.com/rancher/fleet-examples
  paths:
  - single-cluster/manifests
EOF
----
====

== Exemples de grappes multiples

Les exemples ci-dessous permettent de déployer un repo multi git sur plusieurs clusters à la fois et de configurer l'application différemment pour chaque cible.

[tabs,sync-group-id=examples]
====
Tige::
+
Un exemple utilisant Helm. Nous déployons l' https://github.com/rancher/fleet-examples/tree/master/multi-cluster/helm[exemple] et le personnalisons pour chaque cluster cible.
+
Le référentiel contient un diagramme de barre et une option `fleet.yaml` pour configurer le déploiement. Le site `fleet.yaml` permet de configurer différentes options de déploiement, en fonction des étiquettes du cluster :
+
.fleet.yaml
[source,yaml]
----
namespace: fleet-mc-helm-example
targetCustomizations:
- name: dev
  helm:
    values:
      replication: false
  clusterSelector:
    matchLabels:
      env: dev

- name: test
  helm:
    values:
      replicas: 3
  clusterSelector:
    matchLabels:
      env: test

- name: prod
  helm:
    values:
      serviceType: LoadBalancer
      replicas: 3
  clusterSelector:
    matchLabels:
      env: prod
----
+
Pour créer le déploiement, nous appliquons la ressource personnalisée au cluster en amont. L'espace de noms `fleet-default` contient par défaut les ressources du cluster en aval. La carte sera déployée sur tous les clusters de l'espace de noms fleet-default, qui ont une ressource de cluster étiquetée qui correspond à n'importe quelle entrée sous `targets:`.
+
.gitrepo.yaml
[source,yaml]
----
kind: GitRepo
apiVersion: fleet.cattle.io/v1alpha1
metadata:
  name: helm
  namespace: fleet-default
spec:
  repo: https://github.com/rancher/fleet-examples
  paths:
  - multi-cluster/helm
  targets:
  - name: dev
    clusterSelector:
      matchLabels:
        env: dev

  - name: test
    clusterSelector:
      matchLabels:
        env: test

  - name: prod
    clusterSelector:
      matchLabels:
        env: prod
----
+
En appliquant la ressource gitrepo au cluster en amont, fleet commencera à surveiller le dépôt et à créer des déploiements :
+
[source,bash]
----
kubectl apply -n fleet-default -f gitrepo.yaml
----

Barre extérieure::
+
Un https://github.com/rancher/fleet-examples/blob/master/multi-cluster/helm-external[exemple] La personnalisation est similaire à l'exemple précédent.
+
Pour créer le déploiement, nous appliquons la ressource personnalisée au cluster en amont. L'espace de noms `fleet-default` contient par défaut les ressources du cluster en aval. La carte sera déployée sur tous les clusters de l'espace de noms fleet-default, qui ont une ressource de cluster étiquetée qui correspond à n'importe quelle entrée sous `targets:`.
+
.gitrepo.yaml
[source,yaml]
----
kind: GitRepo
apiVersion: fleet.cattle.io/v1alpha1
metadata:
  name: helm-external
  namespace: fleet-default
spec:
  repo: https://github.com/rancher/fleet-examples
  paths:
  - multi-cluster/helm-external
  targets:
  - name: dev
    clusterSelector:
      matchLabels:
        env: dev

  - name: test
    clusterSelector:
      matchLabels:
        env: test

  - name: prod
    clusterSelector:
      matchLabels:
        env: prod
----
+
En appliquant la ressource gitrepo au cluster en amont, fleet commencera à surveiller le dépôt et à créer des déploiements :
+
[source,bash]
----
kubectl apply -n fleet-default -f gitrepo.yaml
----

Barrer et personnaliser::
+
Exemple d'utilisation de https://github.com/rancher/fleet-examples/blob/master/multi-cluster/helm-kustomize[pour modifier une carte Helm d'un tiers.] kustomize Il déploiera l'exemple d'application de livre d'or Kubernetes sous la forme d'un diagramme Helm téléchargé à partir d'une source tierce et modifiera le diagramme Helm à l'aide de Kustomize. L'application sera déployée dans l'espace de noms fleet-helm-kustomize-example. 
+
L'application sera personnalisée comme suit en fonction de l'environnement : 
+
  * Grappes de développement : Seul le leader redis est déployé et non les followers. 
  * Clusters de test : Réduire le déploiement frontal à 3 
  * Clusters Prod : Réduire le déploiement frontal à 3 et définir le type de service à LoadBalancer 
+
Le site `fleet.yaml` est utilisé pour contrôler les recouvrements utilisés, en fonction des étiquettes de la grappe :
+
.fleet.yaml
[source,yaml]
----
namespace: fleet-mc-kustomize-example
targetCustomizations:
- name: dev
  clusterSelector:
    matchLabels:
      env: dev
  kustomize:
    dir: overlays/dev

- name: test
  clusterSelector:
    matchLabels:
      env: test
  kustomize:
    dir: overlays/test

- name: prod
  clusterSelector:
    matchLabels:
      env: prod
  kustomize:
    dir: overlays/prod
----
+
Pour créer le déploiement, nous appliquons la ressource personnalisée au cluster en amont. L'espace de noms `fleet-default` contient par défaut les ressources du cluster en aval. La carte sera déployée sur tous les clusters de l'espace de noms fleet-default, qui ont une ressource de cluster étiquetée qui correspond à n'importe quelle entrée sous `targets:`.
+
.gitrepo.yaml
[source,yaml]
----
kind: GitRepo
apiVersion: fleet.cattle.io/v1alpha1
metadata:
  name: helm-kustomize
  namespace: fleet-default
spec:
  repo: https://github.com/rancher/fleet-examples
  paths:
  - multi-cluster/helm-kustomize
  targets:
  - name: dev
    clusterSelector:
      matchLabels:
        env: dev

  - name: test
    clusterSelector:
      matchLabels:
        env: test

  - name: prod
    clusterSelector:
      matchLabels:
        env: prod
----
+
En appliquant la ressource gitrepo au cluster en amont, fleet commencera à surveiller le dépôt et à créer des déploiements :
+
[source,bash]
----
kubectl apply -n fleet-default -f gitrepo.yaml
----

Kustomize::
+
Un https://github.com/rancher/fleet-examples/blob/master/multi-cluster/kustomize[exemple] et le personnalisant par cluster cible.
+
La personnalisation sur `fleet.yaml` est identique à l'exemple "Helm & Kustomize".
+
Pour créer le déploiement, nous appliquons la ressource personnalisée au cluster en amont. L'espace de noms `fleet-default` contient par défaut les ressources du cluster en aval. La carte sera déployée sur tous les clusters de l'espace de noms fleet-default, qui ont une ressource de cluster étiquetée qui correspond à n'importe quelle entrée sous `targets:`.
+
[source,bash]
----
kubectl apply -n fleet-default -f - <<EOF
kind: GitRepo
apiVersion: fleet.cattle.io/v1alpha1
metadata:
  name: kustomize
  namespace: fleet-default
spec:
  repo: https://github.com/rancher/fleet-examples
  paths:
  - multi-cluster/kustomize
  targets:
  - name: dev
    clusterSelector:
      matchLabels:
        env: dev

  - name: test
    clusterSelector:
      matchLabels:
        env: test

  - name: prod
    clusterSelector:
      matchLabels:
        env: prod
EOF
----
+
En appliquant la ressource gitrepo au cluster en amont, fleet commencera à surveiller le dépôt et à créer des déploiements : 

Manifestes::
+
Un https://github.com/rancher/fleet-examples/tree/master/multi-cluster/manifests[exemple] L'application sera personnalisée comme suit en fonction de l'environnement :
+
* Grappes de développement : Seul le leader redis est déployé et non les followers. 
* Clusters de test : Réduire le déploiement frontal à 3 
* Clusters Prod : Réduire le déploiement frontal à 3 et définir le type de service à LoadBalancer 
+
L'adresse `fleet.yaml` est utilisée pour contrôler les recouvrements 'yaml' qui sont utilisés, en fonction des étiquettes du cluster : 
+
.fleet.yaml
[source,yaml]
----
namespace: fleet-mc-manifest-example
targetCustomizations:
- name: dev
  clusterSelector:
    matchLabels:
      env: dev
  yaml:
    overlays:
    # Refers to overlays/noreplication folder
    - noreplication

- name: test
  clusterSelector:
    matchLabels:
      env: test
  yaml:
    overlays:
    # Refers to overlays/scale3 folder
    - scale3

- name: prod
  clusterSelector:
    matchLabels:
      env: prod
  yaml:
    # Refers to overlays/servicelb, scale3 folders
    overlays:
    - servicelb
    - scale3
----
+
Pour créer le déploiement, nous appliquons la ressource personnalisée au cluster en amont. L'espace de noms `fleet-default` contient par défaut les ressources du cluster en aval. La carte sera déployée sur tous les clusters de l'espace de noms fleet-default, qui ont une ressource de cluster étiquetée qui correspond à n'importe quelle entrée sous `targets:`.
+
.gitrepo.yaml
[source,yaml]
----
kind: GitRepo
apiVersion: fleet.cattle.io/v1alpha1
metadata:
  name: manifests
  namespace: fleet-default
spec:
  repo: https://github.com/rancher/fleet-examples
  paths:
  - multi-cluster/manifests
  targets:
  - name: dev
    clusterSelector:
      matchLabels:
        env: dev

  - name: test
    clusterSelector:
      matchLabels:
        env: test

  - name: prod
    clusterSelector:
      matchLabels:
        env: prod
----
+
[source,bash]
----
kubectl apply -n fleet-default -f gitrepo.yaml
----
====
