= Récupérer les diagrammes de Helm à partir des registres OCI
:revdate: 2025-09-01
:page-revdate: {revdate}

{product_name} permet d'extraire les diagrammes de Helm stockés dans les registres OCI. Les registres OCI sont couramment utilisés pour stocker et distribuer des images de conteneurs. En les utilisant pour les cartes Helm, vous pouvez appliquer les mêmes méthodes de conditionnement, d'authentification et de distribution que celles que vous utilisez déjà pour les images de conteneurs.

L'utilisation des registres OCI pour les cartes Helm vous aide :

* Stocker les diagrammes avec les images de conteneurs dans le même registre.
* Utilisez la même authentification et le même contrôle d'accès que ceux que vous appliquez déjà aux images de conteneurs.
* Les graphiques sont poussés et tirés à l'aide de commandes OCI standard, ce qui permet de les distribuer facilement dans tous les environnements.
* Gérer les cartes dans des registres conçus pour une haute disponibilité et une distribution mondiale.

Pour plus d'informations sur HelmOps avec le registre OCI, voir xref:how-tos-for-users/helm-ops.adoc#oci-registry[HelmOps].

image::fetch-Helm-from-OCI.svg[Une ressource visuelle montrant le flux de récupération des cartes Helm à partir d'un registre OCI]

Par exemple, si vous gérez plusieurs clusters avec {product_name}, les développeurs peuvent envoyer des graphiques Helm à un registre OCI interne. {product_name} extrait alors les graphiques directement du registre et les déploie sur les clusters en aval.
Cette approche permet d'éviter de maintenir un référentiel graphique distinct et de réutiliser l'infrastructure de registre existante.

== Tableau de bord dans fleet.yaml

Pour obtenir une carte Helm, faites référence à la carte comme suit dans un fichier `fleet.yaml`:

[source,yaml]
----
helm:
  chart: "oci://ghcr.io/fleetrepoci/guestbook"
----

Vous pouvez utiliser le champ `version` pour faire référence à une version spécifique de la carte :

[source,yaml]
----
helm:
  chart: "oci://ghcr.io/fleetrepoci/guestbook"
  version: 0.1.0
----

{product_name} extrait la carte du registre OCI et la déploie sur les clusters ciblés.

== Utilisation de registres authentifiés

Si le registre OCI nécessite une authentification, référencez un secret Kubernetes dans la ressource GitRepo. {product_name} utilise ce secret pour extraire le graphique et le déployer sur les clusters ciblés.

Pour plus d'informations, voir xref:how-tos-for-users/gitrepo-add.adoc#_using_private_helm_repositories[fleet.yaml avec authentification].
