= Uso do Image Scan para atualizar referências de imagens de contêineres
:revdate: 2025-04-30
:page-revdate: {revdate}

A varredura de imagens no fleet permite que você faça a varredura do repositório de imagens, busque a imagem desejada e atualize o repositório git, sem a necessidade de atualizar manualmente os manifestos.

[CAUTION]
====

Esse recurso é considerado experimental.
====


Acesse `+fleet.yaml+` e adicione a seguinte seção.

[,yaml]
----
imageScans:
# specify the policy to retrieve images, can be semver or alphabetical order
- policy:
    # if range is specified, it will take the latest image according to semver order in the range
    # for more details on how to use semver, see https://github.com/Masterminds/semver
    semver:
      range: "*"
    # can use ascending or descending order
    alphabetical:
      order: asc

  # specify images to scan
  image: "your.registry.com/repo/image"

  # Specify the tag name, it has to be unique in the same bundle
  tagName: test-scan

  # specify secret to pull image if in private registry
  secretRef:
    name: dockerhub-secret

  # Specify the scan interval
  interval: 5m
----

[IMPORTANT]
====

Você pode criar várias varreduras de imagem em fleet.yaml.
====


[NOTE]
====

O Semver ignorará as versões de pré-lançamento (por exemplo, 0.0.1-10), a menos que uma versão de pré-lançamento seja explicitamente usada na definição do intervalo.
Por exemplo, o intervalo "*" ignorará as versões anteriores, enquanto ">= 0.0.1-10" as levará em consideração.
====


Vá para seus arquivos de manifesto e atualize o campo que deseja substituir. Por exemplo:

[,yaml]
----
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-slave
spec:
  selector:
    matchLabels:
      app: redis
      role: slave
      tier: backend
  replicas: 2
  template:
    metadata:
      labels:
        app: redis
        role: slave
        tier: backend
    spec:
      containers:
      - name: slave
        image: <image>:<tag> # {"$imagescan": "test-scan"}
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 6379
----

[NOTE]
====

Há várias formas de tagName que podem ser referenciadas. Por exemplo

`+{"$imagescan": "test-scan"}+`: Usar o nome completo da imagem (foo/bar:tag)

`+{"$imagescan": "test-scan:name"}+`: Use apenas o nome da imagem sem a tag (foo/bar)

`+{"$imagescan": "test-scan:tag"}+`: Use apenas a tag de imagem

`+{"$imagescan": "test-scan:digest"}+`: Use o nome completo da imagem com o resumo (foo/bar:tag@sha256...)
====


Crie um GitRepo que inclua seu fleet.yaml

[,yaml]
----
kind: GitRepo
apiVersion: fleet.cattle.io/v1alpha1
metadata:
  name: my-repo
  namespace: fleet-local
spec:
  # change this to be your own repo
  repo: https://github.com/rancher/fleet-examples
  # define how long it will sync all the images and decide to apply change
  imageScanInterval: 5m
  # user must properly provide a secret that have write access to git repository
  clientSecretName: secret
  # specify the commit pattern
  imageScanCommit:
    authorName: foo
    authorEmail: foo@bar.com
    messageTemplate: "update image"
----

Tente inserir uma nova tag de imagem, por exemplo, `+<image>:<new-tag>+`. Aguarde um pouco e deverá haver um novo commit enviado para o seu repositório git para alterar a tag em deployment.yaml.
Depois que a alteração for feita no repositório git, o fleet lerá a alteração e a implementará em seu cluster.
