= Einrichtung Mehrbenutzer
:revdate: 2025-04-30
:page-revdate: {revdate}

{product_name} verwendet nach Möglichkeit Kubernetes RBAC.

Eine Ergänzung zu RBAC ist die xref:explanations/namespaces.adoc#_restricting_gitrepos[`GitRepoRestriction`] Ressource, die verwendet werden kann, um GitRepo-Ressourcen in einem Namespace zu kontrollieren.

Eine Multi-User-Flotte sieht wie folgt aus:

* Tenants teilen sich keine Namespaces, jeder Tenant hat einen oder mehrere Namespaces auf dem Upstream-Cluster, wo er GitRepo-Ressourcen erstellen kann
* Mieter können keine clusterweiten Ressourcen bereitstellen und sind auf eine Reihe von Namespaces auf nachgelagerten Clustern beschränkt
* Cluster befinden sich in einem eigenen Namensraum

image::FleetSharedClusters.svg[Gemeinsame Cluster]

[CAUTION]
.wichtige Informationen
====

Die Isolierung von Tenants ist nicht vollständig und hängt von der korrekten Einrichtung von Kubernetes RBAC ab. Ohne manuelle Einrichtung durch einen Operator können die Mieter weiterhin clusterweite Ressourcen einsetzen. Selbst mit den unter {product_name} verfügbaren Einschränkungen sind die Benutzer nur auf Namespaces beschränkt, aber Namespaces bieten für sich genommen kaum Isolierung. Sie können z. B. so viele Ressourcen verbrauchen, wie sie wollen.

Die bestehenden Beschränkungen von {product_name} ermöglichen es den Benutzern jedoch, Cluster gemeinsam zu nutzen und Ressourcen ohne Konflikte einzusetzen.
====


== Beispiel {product_name} Eigenständig

Damit würde ein Benutzer "fleetuser" erstellt, der nur GitRepo-Ressourcen im Namensraum "project1" verwalten kann.

[,bash]
----
 kubectl create serviceaccount fleetuser
 kubectl create namespace project1
 kubectl create -n project1 role fleetuser --verb=get --verb=list --verb=create --verb=delete --resource=gitrepos.fleet.cattle.io
 kubectl create -n project1 rolebinding fleetuser --serviceaccount=default:fleetuser --role=fleetuser
----

Wenn wir Zugang zu mehreren Namensräumen gewähren wollen, können wir eine einzige Clusterrolle mit zwei Rollenbindungen verwenden:

[,bash]
----
 kubectl create clusterrole fleetuser --verb=get --verb=list --verb=create --verb=delete --resource=gitrepos.fleet.cattle.io
 kubectl create -n project1 rolebinding fleetuser --serviceaccount=default:fleetuser --clusterrole=fleetuser
 kubectl create -n project2 rolebinding fleetuser --serviceaccount=default:fleetuser --clusterrole=fleetuser
----

Dies stellt sicher, dass Tenants nicht mit GitRepo-Ressourcen anderer Tenants interferieren können, da sie keinen Zugriff auf deren Namespaces haben.

== Beispiel {product_name} in Rancher

Wenn ein neuer Flottenarbeitsbereich erstellt wird, wird automatisch ein entsprechender Namensbereich mit identischem Namen innerhalb des lokalen Rancher-Clusters erzeugt.
Damit ein Benutzer Flottenressourcen in einem bestimmten Arbeitsbereich sehen und einsetzen kann, benötigt er mindestens die folgenden Berechtigungen:

* Auflisten/Abrufen der `fleetworkspace` clusterweiten Ressource im lokalen Cluster
* Berechtigung zum Erstellen von Flottenressourcen (wie `bundles`, `gitrepos`, ...) im Backing-Namensraum für den Arbeitsbereich im lokalen Cluster.

Erteilen wir die Berechtigung zur Bereitstellung von Flottenressourcen in den Flottenarbeitsbereichen `project1` und `project2`:

ifeval::["{product}" == "fleet"]
* Um die Flottenarbeitsbereiche `project1` und `project2` zu erstellen, können Sie dies entweder in der https://ranchermanager.docs.rancher.com/integrations-in-rancher/fleet/overview#accessing-fleet-in-the-rancher-ui[Rancher-Benutzeroberfläche] tun oder die folgenden YAML-Ressourcen verwenden:
endif::[]

ifeval::["{product}" == "continuous-delivery"]

* Um die Flottenarbeitsbereiche `project1` und `project2` zu erstellen, können Sie dies entweder in der https://documentation.suse.com/cloudnative/rancher-manager/latest/en/integrations/fleet/overview.html#_accessing_suse_rancher_prime_continuous_delivery_in_the_rancher_ui[Rancher-Benutzeroberfläche] tun oder die folgenden YAML-Ressourcen verwenden:

[,yaml]
----
apiVersion: management.cattle.io/v3
kind: FleetWorkspace
metadata:
  name: project1
----

[,yaml]
----
apiVersion: management.cattle.io/v3
kind: FleetWorkspace
metadata:
  name: project2
----

* Erstellen Sie eine `GlobalRole`, die die Berechtigung zur Bereitstellung von Flottenressourcen in den Flottenarbeitsbereichen `project1` und `project2` erteilt:

[,yaml]
----
apiVersion: management.cattle.io/v3
kind: GlobalRole
metadata:
  name: fleet-projects1and2
namespacedRules:
  project1:
    - apiGroups:
        - fleet.cattle.io
      resources:
        - gitrepos
        - bundles
        - clusterregistrationtokens
        - gitreporestrictions
        - clusters
        - clustergroups
      verbs:
        - '*'
  project2:
    - apiGroups:
        - fleet.cattle.io
      resources:
        - gitrepos
        - bundles
        - clusterregistrationtokens
        - gitreporestrictions
        - clusters
        - clustergroups
      verbs:
        - '*'
rules:
  - apiGroups:
      - management.cattle.io
    resourceNames:
      - project1
      - project2
    resources:
      - fleetworkspaces
    verbs:
      - '*'
----

ifeval::["{product}" == "fleet"]
Weisen Sie die `GlobalRole` Benutzern oder Gruppen zu. Weitere Informationen finden Sie in den https://ranchermanager.docs.rancher.com/how-to-guides/new-user-guides/authentication-permissions-and-global-configuration/manage-role-based-access-control-rbac/global-permissions#configuring-global-permissions-for-individual-users[Rancher-Dokumenten].
endif::[]

ifeval::["{product}" == "continuous-delivery"]

Weisen Sie die `GlobalRole` Benutzern oder Gruppen zu. Weitere Informationen finden Sie in den https://documentation.suse.com/cloudnative/rancher-manager/v2.12/en/rancher-admin/users/authn-and-authz/manage-role-based-access-control-rbac/global-permissions.html#_configuring_global_permissions_for_individual_users[Rancher-Dokumenten].
endif::[]

Der Benutzer hat nun Zugriff auf die Registerkarte `Continuous Delivery` in Rancher und kann Ressourcen sowohl in den `project1` als auch in den `project2` Arbeitsbereichen bereitstellen.

Um eine gut organisierte Umgebung zu schaffen, sollte jeder Arbeitsbereich über einen eigenen `GlobalRole` verfügen, um die vom Kunden geforderte Aufgabentrennung und Isolierung zu gewährleisten. Auf diese Weise kann jeder Benutzer je nach Bedarf einem oder mehreren `GlobalRoles` zugewiesen werden.

== Zugang zu Clustern zulassen

Dies setzt voraus, dass alle von "fleetuser" erstellten GitRepos das Label `team: one` haben. Es können unterschiedliche Bezeichnungen verwendet werden, um verschiedene Cluster-Namensräume auszuwählen.

Erstellen Sie als Administrator in jedem der Namensräume des Benutzers eine xref:explanations/namespaces.adoc#_cross_namespace_deployments[`BundleNamespaceMapping`].

[,yaml]
....
kind: BundleNamespaceMapping
apiVersion: fleet.cattle.io/v1alpha1
metadata:
  name: mapping
  namespace: project1

# Bundles to match by label.
# The labels are defined in the fleet.yaml # labels field or from the
# GitRepo metadata.labels field
bundleSelector:
  matchLabels:
    team: one
    # or target one repo
    #fleet.cattle.io/repo-name: simpleapp

# Namespaces, containing clusters, to match by label
namespaceSelector:
  matchLabels:
    kubernetes.io/metadata.name: fleet-default
    # the label is on the namespace
    #workspace: prod
....

Der xref:how-tos-for-users/gitrepo-targets.adoc[Abschnitt`target` ] in der GitRepo-Ressource kann verwendet werden, um nur eine Teilmenge der übereinstimmenden Cluster bereitzustellen.

== Beschränkung des Zugangs zu nachgelagerten Clustern

Admins können Tenants weiter einschränken, indem sie in jedem ihrer Namespaces eine `GitRepoRestriction` erstellen.

[,yaml]
....
kind: GitRepoRestriction
apiVersion: fleet.cattle.io/v1alpha1
metadata:
  name: restriction
  namespace: project1

allowedTargetNamespaces:
  - project1simpleapp
....

Dadurch wird die Erstellung von clusterweiten Ressourcen verweigert, die andere Tenants beeinträchtigen könnten, und die Bereitstellung wird auf den Namensraum "project1simpleapp" beschränkt.

== Ein Beispiel für eine GitRepo-Ressource

Eine GitRepo-Ressource, die von einem Tenant ohne Admin-Zugang erstellt wurde, könnte wie folgt aussehen:

[,yaml]
....
kind: GitRepo
apiVersion: fleet.cattle.io/v1alpha1
metadata:
  name: simpleapp
  namespace: project1
  labels:
    team: one

spec:
  repo: https://github.com/rancher/fleet-examples
  paths:
  - bundle-diffs

  targetNamespace: project1simpleapp

  # do not match the upstream/local cluster, won't work
  targets:
  - name: dev
    clusterSelector:
      matchLabels:
        env: dev
....

Dazu gehören das Etikett `team: one` und die erforderliche `targetNamespace`.

Zusammen mit dem vorherigen `BundleNamespaceMapping` würde dies alle Cluster mit einem `env: dev` Label im "fleet-default" Namensraum betreffen.

[NOTE]
====

`BundleNamespaceMappings` funktionieren nicht mit lokalen Clustern, stellen Sie also sicher, dass Sie diese nicht anvisieren.
====

