= 変更された建築
:revdate: 2025-04-30
:page-revdate: {revdate}

{product_name} には2つの主要コンポーネントがある。{product_name} コントローラとクラスタエージェント。これらのコンポーネントは、2段階のプルモデルで機能する。{product_name} コントローラは git からプルし、クラスタエージェントは{product_name} コントローラからプルします。

== {product_name} コントローラー

{product_name} コントローラは、標準的なKubernetesクラスタで動作するKubernetesコントローラのセットである。 {product_name} コントローラーが公開するAPIはKubernetes APIのみで、フリートコントローラー用のカスタムAPIはない。

== クラスター・エージェント

各クラスタで1つのクラスタエージェントが実行され、{product_name} コントローラとの通信を担当します。
クラスタから{product_name} コントローラへの通信はこのエージェントによってのみ行われ、すべての通信は管理されたクラスタから{product_name} コントローラへ行われます。フリートコントローラは、ダウンストリームクラスタへの接続を開始しない。これは、マネージド・クラスターがプライベート・ネットワークやNATの背後で稼働できることを意味する。唯一の要件は、クラスタエージェントが{product_name} コントローラを実行しているクラスタの Kubernetes API と通信できる必要があることだ。この例外は、xref:how-tos-for-operators/cluster-registration.adoc#_manager_initiated[マネージャ主導の]クラスタ登録フローを使用する場合です。これは必須ではなく、オプションのパターンである。

クラスタエージェントは「常時接続」を前提としていない。接続が可能になり次第、すぐに運転を再開する。将来の機能拡張では、エージェントがチェックインする時間をスケジュールする機能が追加されるだろう。

== セキュリティ

{product_name} コントローラーは、動的にサービスアカウントを作成し、そのRBACを管理し、下流のクラスタにトークンを渡す。クラスターは、オプションでクラスター登録トークンの有効期限を設定することで登録される。
クラスタ登録トークンは、そのクラスタに固有のクレデンシャルを生成するための登録プロセス中にのみ使用される。クラスタ・クレデンシャルが確立されると、クラスタはクラスタ登録トークンを「忘れる」。

クラスタに与えられたサービス・アカウントは、そのクラスタ専用に作成された名前空間の`BundleDeployment` をリストする権限しか持っていません。また、`BundleDeployment` の`status` サブリソースと、その`Cluster` リソースの`status`サブリソースを更新することもできる。

== コンポーネントの概要

各コンポーネントの概要と、それらがハイレベルでどのように相互作用するかを説明する。

image::FleetComponents.svg[静的, 600]
