= 下流クラスターへのマッピング
:revdate: 2025-04-30
:page-revdate: {revdate}

ifeval::["{product}" == "fleet"]
https://ranchermanager.docs.rancher.com/integrations-in-rancher/fleet[{product_name} のRancherを]使えば、クラスタをあたかも1つのクラスタのように簡単に管理できる。ユーザーは、デプロイメントマニフェストやその他のKubernetesリソースで構成されるバンドルを、グルーピング設定を使用してクラスタ間でデプロイできる。

endif::[]

ifeval::["{product}" == "continuous-delivery"]
https://documentation.suse.com/cloudnative/rancher-manager/latest/en/integrations/fleet/overview.html[{product_name} のRancherを]使えば、クラスタをあたかも1つのクラスタのように簡単に管理できる。ユーザーは、デプロイメントマニフェストやその他のKubernetesリソースで構成されるバンドルを、グルーピング設定を使用してクラスタ間でデプロイできる。
endif::[]
[IMPORTANT]
====

*マルチクラスタのみ*：
この方法は、マルチクラスタ・スタイルで{product_name} を実行している場合にのみ適用されます。 ターゲットが指定されていない場合、つまりシングルクラスタを使用している場合、バンドルはデフォルトのクラスタ・グループをターゲットにします。
====


`GitRepos` を下流のクラスタにデプロイする場合は、クラスタをターゲットにマッピングする必要があります。

== ターゲットの定義

`GitRepo` のデプロイ対象は、`spec.targets` フィールドを使用してクラスタまたはクラスタ・グループに一致させます。YAMLの仕様は以下の通りです。

[,yaml]
----
kind: GitRepo
apiVersion: fleet.cattle.io/v1alpha1
metadata:
  name: myrepo
  namespace: clusters
spec:
  repo: https://github.com/rancher/fleet-examples
  paths:
  - simple

  # Targets are evaluated in order and the first one to match is used. If
  # no targets match then the evaluated cluster will not be deployed to.
  targets:
  # The name of target. This value is largely for display and logging.
  # If not specified a default name of the format "target000" will be used
  - name: prod
    # A selector used to match clusters.  The structure is the standard
    # metav1.LabelSelector format. If clusterGroupSelector or clusterGroup is specified,
    # clusterSelector will be used only to further refine the selection after
    # clusterGroupSelector and clusterGroup is evaluated.
    clusterSelector:
      matchLabels:
        env: prod
    # A selector used to match cluster groups.
    clusterGroupSelector:
      matchLabels:
        region: us-east
    # A specific clusterGroup by name that will be selected
    clusterGroup: group1
    # A specific cluster by name that will be selected
    clusterName: cluster1
----

== ターゲット・マッチング

`GitRepo` と同じネームスペースにあるすべてのクラスタとクラスタグループが、すべてのターゲットに対して評価されます。
ターゲットのいずれかがクラスタに一致する場合、`GitRepo` 、ダウンストリームクラスタにデプロイされる。一致しない場合は、`GitRepo` 、そのクラスタにはデプロイされません。

クラスターのマッチングには3つのアプローチがある。
クラスタ・セレクタ、クラスタ・グループ・セレクタ、あるいは明示的なクラスタ・グループ名を使うことができる。 すべての基準は加算されるので、最終的なマッチは "clusterSelector && clusterGroupSelector && clusterGroup "として評価される。 もし3つのうちどれかがデフォルト値であれば、それは基準から外される。 デフォルト値はnullまたは""。 セレクタの値`{}` は、"すべてにマッチする "という意味であることを理解することが重要である。

[,yaml]
----
targets:
  # Match everything
  - clusterSelector: {}
  # Selector ignored
  - clusterSelector: null
----

クラスターを名前でマッチさせることもできる：

[,yaml]
----
targets:
  - clusterName: fleetname
----

Rancherで{product_name} 、必ず`clusters.fleet.cattle.io` リソースの名前を入れてください。

== デフォルトターゲット

`GitRepo` にターゲットが設定されていない場合は、デフォルトのターゲット値が適用される。 デフォルトの目標値は以下の通り。

[,yaml]
----
targets:
- name: default
  clusterGroup: default
----

つまり、GitRepos を設定しないデフォルトの場所を設定したい場合は、default という名前のクラスタグループを作成してそこにクラスタを追加すればいいのです。

== クラスタごとのカスタマイズ

[IMPORTANT]
====

`GitRepo` リソースの`targets:` は、デプロイするクラスタを選択する。`fleet.yaml` の`targetCustomizations:` はHelmの値のみを上書きし、ターゲティングは変更しない。
====


Kubernetesマニフェストを、{product_name} を使用してカスタマイズしながら異なるクラスタにデプロイする方法を示すために、https://github.com/rancher/fleet-examples/blob/master/multi-cluster/helm/fleet.yaml[multi-cluster/helm/fleet.yaml] を使用します。

*状況は？*ユーザーには、3つの異なるラベルを持つ3つのクラスターがある：`env=dev` `env=test` および`env=prod` 。ユーザーは、バックエンドデータベースを持つフロントエンドアプリケーションを、これらのクラスタにデプロイしたいと考えています。

*期待される行動*

* `dev` クラスタにデプロイした後、データベースのレプリケーションが有効になりません。
* `test` クラスタにデプロイすると、データベースのレプリケーションが有効になります。
* `prod` クラスタにデプロイすると、データベースのレプリケーションが有効になり、 ロードバランサのサービスが公開されます。

*{product_name} の利点：*

各クラスタにアプリをデプロイする代わりに、{product_name} 、以下の手順ですべてのクラスタにデプロイできる：

. gitRepo`https://github.com/rancher/fleet-examples.git` をデプロイし、パス`multi-cluster/helm` を指定してください。
. `multi-cluster/helm` 、Helmチャートがフロントエンドのアプリ・サービスとバックエンドのデータベース・サービスをデプロイする。
. 以下のルールは、`fleet.yaml` で定義される：

----
targetCustomizations:
- name: dev
  helm:
    values:
      replication: false
  clusterSelector:
    matchLabels:
      env: dev

- name: test
  helm:
    values:
      replicas: 3
  clusterSelector:
    matchLabels:
      env: test

- name: prod
  helm:
    values:
      serviceType: LoadBalancer
      replicas: 3
  clusterSelector:
    matchLabels:
      env: prod
----

*結果*

{product_name} は、カスタマイズした`values.yaml` を含む Helm チャートを異なるクラスタにデプロイします。

NOTE: 構成管理はデプロイメントに限定されるものではなく、一般的な構成管理に拡張することができる。{product_name} 、任意のクラスタ・セット間でカスタマイズによる構成管理を自動的に適用することができる。

=== サポートされるカスタマイズ

* xref:reference/ref-crds.adoc#_bundledeploymentoptions[DefaultNamespace]
* xref:reference/ref-crds.adoc#_bundledeploymentoptions[ForceSyncGeneration]
* xref:reference/ref-crds.adoc#_bundledeploymentoptions[KeepResources]
* xref:reference/ref-crds.adoc#_bundledeploymentoptions[サービスアカウント]
* xref:reference/ref-crds.adoc#_bundledeploymentoptions[TargetNamespace]
* xref:reference/ref-crds.adoc#_helmoptions[ヘルム・アトミック]
* xref:reference/ref-crds.adoc#_helmoptions[Helm.Chart]
* xref:reference/ref-crds.adoc#_helmoptions[Helm.DisablePreProcess]
* xref:reference/ref-crds.adoc#_helmoptions[Helm.Force]
* xref:reference/ref-crds.adoc#_helmoptions[Helm.ReleaseName]
* xref:reference/ref-crds.adoc#_helmoptions[Helm.Repo]
* xref:reference/ref-crds.adoc#_helmoptions[Helm.TakeOwnership]
* xref:reference/ref-crds.adoc#_helmoptions[Helm.TimeoutSeconds]
* xref:reference/ref-crds.adoc#_helmoptions[Helm.ValuesFrom]
* xref:reference/ref-crds.adoc#_helmoptions[Helm.Values]
* xref:reference/ref-crds.adoc#_helmoptions[ヘルムバージョン]
+

[CAUTION]
.重要情報
====
ターゲットのカスタマイズによってHelmチャートのバージョンを上書きすると、_すべての_クラスタに対応するために、デフォルトとカスタムの_すべての_バージョンのチャートを含むバンドルが作成されます。これは、{product_name} 、より大きなバンドルが配備されることを意味する。
+
{product_name} 、etcd経由でバンドルが保存されるため、クラスタによってはバンドル・サイズがetcdの設定した最大ブロブ・サイズを超える問題が発生する可能性がある。詳細はhttps://github.com/rancher/fleet/issues/1650[] を参照のこと。
====


* xref:reference/ref-crds.adoc#_helmoptions[Helm.WaitForJobs]
* xref:reference/ref-crds.adoc#_kustomizeoptions[Kustomize.Dir]
* xref:reference/ref-crds.adoc#_yamloptions[YAML.オーバーレイ]
* xref:reference/ref-crds.adoc#_diffoptions[Diff.ComparePatches]

== その他の例

生のKubernetes YAML、Helmチャート、Kustomize、および3つの組み合わせを使用した例は、https://github.com/rancher/fleet-examples/[{product_name} Examplesレポに]あります。
