= Utilisation de la numérisation d'images pour mettre à jour les références de l'image du conteneur
:revdate: 2025-04-30
:page-revdate: {revdate}

Le scan d'images dans fleet vous permet de scanner votre dépôt d'images, de récupérer l'image désirée et de mettre à jour votre dépôt git, sans avoir besoin de mettre à jour manuellement vos manifestes.

[CAUTION]
====

Cette fonction est considérée comme expérimentale.
====


Allez sur `fleet.yaml` et ajoutez la section suivante.

[,yaml]
----
imageScans:
# specify the policy to retrieve images, can be semver or alphabetical order
- policy:
    # if range is specified, it will take the latest image according to semver order in the range
    # for more details on how to use semver, see https://github.com/Masterminds/semver
    semver:
      range: "*"
    # can use ascending or descending order
    alphabetical:
      order: asc

  # specify images to scan
  image: "your.registry.com/repo/image"

  # Specify the tag name, it has to be unique in the same bundle
  tagName: test-scan

  # specify secret to pull image if in private registry
  secretRef:
    name: dockerhub-secret

  # Specify the scan interval
  interval: 5m
----

[IMPORTANT]
====

Vous pouvez créer plusieurs analyses d'images dans fleet.yaml.
====


[NOTE]
====

Semver ne tient pas compte des versions antérieures (par exemple, 0.0.1-10), sauf si une version antérieure est explicitement utilisée dans la définition de l'intervalle.
Par exemple, l'intervalle "*" ignorera les préversions, tandis que ">= 0.0.1-10" les prendra en compte.
====


Allez dans vos fichiers de manifeste et mettez à jour le champ que vous souhaitez remplacer. Par exemple :

[,yaml]
----
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-slave
spec:
  selector:
    matchLabels:
      app: redis
      role: slave
      tier: backend
  replicas: 2
  template:
    metadata:
      labels:
        app: redis
        role: slave
        tier: backend
    spec:
      containers:
      - name: slave
        image: <image>:<tag> # {"$imagescan": "test-scan"}
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 6379
----

[NOTE]
====

Il existe plusieurs formes de nom de balise auxquelles vous pouvez faire référence. Par exemple

`{"$imagescan": "test-scan"}`: Utiliser le nom complet de l'image (foo/bar:tag)

`{"$imagescan": "test-scan:name"}`: N'utiliser que le nom de l'image sans balise (foo/bar)

`{"$imagescan": "test-scan:tag"}`: Utiliser uniquement la balise image

`{"$imagescan": "test-scan:digest"}`: Utiliser le nom complet de l'image avec un condensé (foo/bar:tag@sha256...)
====


Créer une GitRepo qui inclut votre fleet.yaml

[,yaml]
----
kind: GitRepo
apiVersion: fleet.cattle.io/v1alpha1
metadata:
  name: my-repo
  namespace: fleet-local
spec:
  # change this to be your own repo
  repo: https://github.com/rancher/fleet-examples
  # define how long it will sync all the images and decide to apply change
  imageScanInterval: 5m
  # user must properly provide a secret that have write access to git repository
  clientSecretName: secret
  # specify the commit pattern
  imageScanCommit:
    authorName: foo
    authorEmail: foo@bar.com
    messageTemplate: "update image"
----

Essayez d'insérer une nouvelle balise d'image, par exemple, `<image>:<new-tag>`. Attendez un peu et il devrait y avoir un nouveau commit poussé dans votre dépôt git pour changer la balise dans deployment.yaml.
Une fois les modifications apportées au dépôt git, fleet les lira et les déploiera dans votre cluster.
