= 设置多用户
:revdate: 2025-04-30
:page-revdate: {revdate}

{product_name} 尽可能使用 Kubernetes RBAC。

在 RBAC 的基础上增加了 xref:explanations/namespaces.adoc#_restricting_gitrepos[`+GitRepoRestriction+`]资源，可用于控制命名空间中的 GitRepo 资源。

多用户机群设置如下：

* 租户不共享命名空间，每个租户在上游集群上都有一个或多个命名空间，可以在其中创建 GitRepo 资源
* 租户无法部署整个集群的资源，只能在下游集群上使用一组命名空间
* 集群位于单独的命名空间中

image::FleetSharedClusters.svg[共享集群]

[CAUTION]
.重要信息
====

租户的隔离并不完全，需要依赖 Kubernetes RBAC 的正确设置。无需操作员手动设置，租户仍可部署集群范围内的资源。即使有可用的{product_name} 限制，用户也只能受限于命名空间，但命名空间本身并不能提供多少隔离。例如，他们仍然可以随意消耗资源。

不过，现有的{product_name} 限制允许用户共享集群，并在不发生冲突的情况下部署资源。
====


== 示例{product_name} 单机版

这将创建一个用户 "fleetuser"，他只能管理 "project1 "命名空间中的 GitRepo 资源。

[,bash]
----
 kubectl create serviceaccount fleetuser
 kubectl create namespace project1
 kubectl create -n project1 role fleetuser --verb=get --verb=list --verb=create --verb=delete --resource=gitrepos.fleet.cattle.io
 kubectl create -n project1 rolebinding fleetuser --serviceaccount=default:fleetuser --role=fleetuser
----

如果我们要访问多个命名空间，可以使用一个群集角色和两个角色绑定：

[,bash]
----
 kubectl create clusterrole fleetuser --verb=get --verb=list --verb=create --verb=delete --resource=gitrepos.fleet.cattle.io
 kubectl create -n project1 rolebinding fleetuser --serviceaccount=default:fleetuser --clusterrole=fleetuser
 kubectl create -n project2 rolebinding fleetuser --serviceaccount=default:fleetuser --clusterrole=fleetuser
----

这就确保了租户无法干扰其他租户的 GitRepo 资源，因为他们无法访问这些租户的命名空间。

== {product_name} Rancher 中的示例

创建新的舰队工作区时，Rancher 本地群集中会自动生成名称相同的相应命名空间。
用户要查看和部署特定工作区中的机群资源，至少需要以下权限：

* 列出/获取本地群集中的`+fleetworkspace+` 全群集资源
* 在本地群集工作空间的后备命名空间中创建舰队资源（如`+bundles+`,`+gitrepos+`,... ）的权限。

让我们授予在`+project1+` 和`+project2+` 机群工作区部署机群资源的权限：

ifeval::["{product}" == "fleet"]
* 要创建`+project1+` 和`+project2+` 机群工作区，可以在https://ranchermanager.docs.rancher.com/integrations-in-rancher/fleet/overview#accessing-fleet-in-the-rancher-ui[UI 中] Rancher完成，也可以使用以下 YAML 资源：
endif::[]

ifeval::["{product}" == "continuous-delivery"]

* 要创建`+project1+` 和`+project2+` 机群工作区，可以在https://documentation.suse.com/cloudnative/rancher-manager/latest/en/integrations/fleet/overview.html#_accessing_suse_rancher_prime_continuous_delivery_in_the_rancher_ui[UI 中] Rancher完成，也可以使用以下 YAML 资源：

[,yaml]
----
apiVersion: management.cattle.io/v3
kind: FleetWorkspace
metadata:
  name: project1
----

[,yaml]
----
apiVersion: management.cattle.io/v3
kind: FleetWorkspace
metadata:
  name: project2
----

* 创建`+GlobalRole+` ，授予在`+project1+` 和`+project2+` 机群工作区部署机群资源的权限：

[,yaml]
----
apiVersion: management.cattle.io/v3
kind: GlobalRole
metadata:
  name: fleet-projects1and2
namespacedRules:
  project1:
    - apiGroups:
        - fleet.cattle.io
      resources:
        - gitrepos
        - bundles
        - clusterregistrationtokens
        - gitreporestrictions
        - clusters
        - clustergroups
      verbs:
        - '*'
  project2:
    - apiGroups:
        - fleet.cattle.io
      resources:
        - gitrepos
        - bundles
        - clusterregistrationtokens
        - gitreporestrictions
        - clusters
        - clustergroups
      verbs:
        - '*'
rules:
  - apiGroups:
      - management.cattle.io
    resourceNames:
      - project1
      - project2
    resources:
      - fleetworkspaces
    verbs:
      - '*'
----

ifeval::["{product}" == "fleet"]
将`+GlobalRole+` 分配给用户或组，更多信息请参见https://ranchermanager.docs.rancher.com/how-to-guides/new-user-guides/authentication-permissions-and-global-configuration/manage-role-based-access-control-rbac/global-permissions#configuring-global-permissions-for-individual-users[文档] Rancher
endif::[]

ifeval::["{product}" == "continuous-delivery"]

将`+GlobalRole+` 分配给用户或组，更多信息请参见https://documentation.suse.com/cloudnative/rancher-manager/v2.12/en/rancher-admin/users/authn-and-authz/manage-role-based-access-control-rbac/global-permissions.html#_configuring_global_permissions_for_individual_users[文档] Rancher
endif::[]

现在，用户可以访问 Rancher 中的`+Continuous Delivery+` 选项卡，并将资源部署到`+project1+` 和`+project2+` 工作区。

为了营造一个井然有序的环境，每个工作区都应有自己的相关`+GlobalRole+` ，以帮助实现客户要求的职责分离和隔离。这样，每个用户都可以根据需要被分配到一个或多个`+GlobalRoles+` 。

== 允许访问群集

假定 "fleetuser "创建的所有 GitRepos 都带有`+team: one+` 标签。可以使用不同的标签来选择不同的集群命名空间。

在每个用户的命名空间中，以管理员身份创建一个 xref:explanations/namespaces.adoc#_cross_namespace_deployments[`+BundleNamespaceMapping+`].

[,yaml]
....
kind: BundleNamespaceMapping
apiVersion: fleet.cattle.io/v1alpha1
metadata:
  name: mapping
  namespace: project1

# Bundles to match by label.
# The labels are defined in the fleet.yaml # labels field or from the
# GitRepo metadata.labels field
bundleSelector:
  matchLabels:
    team: one
    # or target one repo
    #fleet.cattle.io/repo-name: simpleapp

# Namespaces, containing clusters, to match by label
namespaceSelector:
  matchLabels:
    kubernetes.io/metadata.name: fleet-default
    # the label is on the namespace
    #workspace: prod
....

GitRepo 资源中的xref:how-tos-for-users/gitrepo-targets.adoc[`+target+` 部分]可用于只部署到匹配集群的子集。

== 限制访问下游群集

管理员可以通过在每个租户的命名空间中创建`+GitRepoRestriction+` 来进一步限制租户。

[,yaml]
....
kind: GitRepoRestriction
apiVersion: fleet.cattle.io/v1alpha1
metadata:
  name: restriction
  namespace: project1

allowedTargetNamespaces:
  - project1simpleapp
....

这将拒绝创建可能干扰其他租户的集群范围资源，并将部署限制在 "project1simpleapp "命名空间内。

== GitRepo 资源示例

没有管理员权限的租户创建的 GitRepo 资源可能如下所示：

[,yaml]
....
kind: GitRepo
apiVersion: fleet.cattle.io/v1alpha1
metadata:
  name: simpleapp
  namespace: project1
  labels:
    team: one

spec:
  repo: https://github.com/rancher/fleet-examples
  paths:
  - bundle-diffs

  targetNamespace: project1simpleapp

  # do not match the upstream/local cluster, won't work
  targets:
  - name: dev
    clusterSelector:
      matchLabels:
        env: dev
....

这包括`+team: one+` 标签和所需的`+targetNamespace+` 。

加上之前的`+BundleNamespaceMapping+` ，它将针对 "舰队-默认 "命名空间中带有`+env: dev+` 标签的所有集群。

[NOTE]
====

`+BundleNamespaceMappings+` 对本地群集不起作用，因此请确保不要将其作为目标。
====

