= Verwenden von Image Scan zur Aktualisierung von Container-Image-Referenzen
:revdate: 2025-04-30
:page-revdate: {revdate}

Image Scan in Fleet ermöglicht es Ihnen, Ihr Image-Repository zu scannen, das gewünschte Image zu holen und Ihr Git-Repository zu aktualisieren, ohne dass Sie Ihre Manifeste manuell aktualisieren müssen.

[CAUTION]
====

Diese Funktion wird als experimentelle Funktion betrachtet.
====


Gehen Sie zu `fleet.yaml` und fügen Sie den folgenden Abschnitt hinzu.

[,yaml]
----
imageScans:
# specify the policy to retrieve images, can be semver or alphabetical order
- policy:
    # if range is specified, it will take the latest image according to semver order in the range
    # for more details on how to use semver, see https://github.com/Masterminds/semver
    semver:
      range: "*"
    # can use ascending or descending order
    alphabetical:
      order: asc

  # specify images to scan
  image: "your.registry.com/repo/image"

  # Specify the tag name, it has to be unique in the same bundle
  tagName: test-scan

  # specify secret to pull image if in private registry
  secretRef:
    name: dockerhub-secret

  # Specify the scan interval
  interval: 5m
----

[IMPORTANT]
====

Sie können in fleet.yaml mehrere Image-Scans erstellen.
====


[NOTE]
====

Semver ignoriert Vorabversionen (z. B. 0.0.1-10), es sei denn, in der Bereichsdefinition wird ausdrücklich eine Vorabversion verwendet.
Der Bereich "*" ignoriert zum Beispiel Vorabversionen, während ">= 0.0.1-10" diese berücksichtigt.
====


Gehen Sie zu Ihren Manifestdateien und aktualisieren Sie das Feld, das Sie ersetzen möchten. Zum Beispiel:

[,yaml]
----
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-slave
spec:
  selector:
    matchLabels:
      app: redis
      role: slave
      tier: backend
  replicas: 2
  template:
    metadata:
      labels:
        app: redis
        role: slave
        tier: backend
    spec:
      containers:
      - name: slave
        image: <image>:<tag> # {"$imagescan": "test-scan"}
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 6379
----

[NOTE]
====

Es gibt mehrere Formen von tagName, auf die Sie Bezug nehmen können. Zum Beispiel

`{"$imagescan": "test-scan"}`: Vollständigen Bildnamen verwenden (foo/bar:tag)

`{"$imagescan": "test-scan:name"}`: Nur Bildnamen ohne Tag verwenden (foo/bar)

`{"$imagescan": "test-scan:tag"}`: Nur Bild-Tag verwenden

`{"$imagescan": "test-scan:digest"}`: Vollständigen Bildnamen mit Digest verwenden (foo/bar:tag@sha256...)
====


Erstellen Sie ein GitRepo, das Ihre fleet.yaml enthält

[,yaml]
----
kind: GitRepo
apiVersion: fleet.cattle.io/v1alpha1
metadata:
  name: my-repo
  namespace: fleet-local
spec:
  # change this to be your own repo
  repo: https://github.com/rancher/fleet-examples
  # define how long it will sync all the images and decide to apply change
  imageScanInterval: 5m
  # user must properly provide a secret that have write access to git repository
  clientSecretName: secret
  # specify the commit pattern
  imageScanCommit:
    authorName: foo
    authorEmail: foo@bar.com
    messageTemplate: "update image"
----

Versuchen Sie, ein neues Bild-Tag einzufügen, z. B. `<image>:<new-tag>`. Warten Sie eine Weile und es sollte ein neuer Commit in Ihr Git-Repository geschoben werden, um das Tag in deployment.yaml zu ändern.
Sobald eine Änderung im Git-Repository vorgenommen wurde, liest fleet die Änderung durch und stellt sie in Ihrem Cluster bereit.
