= Désinstaller
:revdate: 2025-07-23
:page-revdate: {revdate}

[CAUTION]
====
La suppression des CRD entraîne la suppression de toutes les charges de travail déployées.
====


== {product_name} Autonome

{product_name} est fourni sous la forme de deux cartes Helm, de sorte que la désinstallation s'effectue en désinstallant les cartes Helm appropriées.

Cependant, {product_name} utilise les https://kubernetes.io/docs/concepts/overview/working-with-objects/finalizers/[finaliseurs de], donc désinstallez d'abord les charges de travail pour donner aux contrôleurs de {product_name} le temps de faire le ménage.

[source,shell]
----
kubectl delete clusters.fleet.cattle.io -A
kubectl delete gitrepos -A
kubectl delete bundles -A
----

Notez qu'il peut être plus facile de supprimer les espaces de noms contenant les charges de travail, par exemple :

[source,shell]
----
kubectl delete ns fleet-local
kubectl delete ns fleet-default
----

Les ressources personnalisées ne sont pas désinstallées par Helm 3, supprimez-les d'abord :

[source,shell]
----
kubectl delete crd gitrepos.fleet.cattle.io bundles.fleet.cattle.io contents.fleet.cattle.io \
  bundledeployments.fleet.cattle.io imagescans.fleet.cattle.io \
  bundlenamespacemappings.fleet.cattle.io gitreporestrictions.fleet.cattle.io \
  clusters.fleet.cattle.io clustergroups.fleet.cattle.io \
  clusterregistrations.fleet.cattle.io clusterregistrationtokens.fleet.cattle.io
----

Ensuite, pour désinstaller {product_name}, exécutez les commandes suivantes :

[,shell]
----
helm -n cattle-fleet-system uninstall fleet
helm -n cattle-fleet-system uninstall fleet-crd
----

[NOTE]
====
Si la désinstallation se bloque, c'est probablement à cause des finaliseurs. Les champs relatifs à l'état des ressources, par exemple dans un espace de noms, dressent la liste des ressources en attente de la suppression de leurs finaliseurs. Les finaliseurs peuvent être supprimés manuellement avec kubectl, si leurs contrôleurs ne fonctionnent plus.
====


Par la suite, il est également possible de supprimer les espaces de noms liés à {product_name} et leur contenu :

[source,shell]
----
kubectl delete ns cattle-fleet-system
kubectl delete ns cattle-fleet-clusters-system
kubectl delete ns -l "fleet.cattle.io/managed=true"
----

== {product_name} dans Rancher

{product_name} dans Rancher ne peut pas être désinstallé sans désinstaller Rancher. Cependant, la fonction GitOps peut être désactivée.
Lorsqu'il est désactivé, le déploiement de gitjob n'est plus déployé dans le cluster local du serveur Rancher, et la livraison continue n'est pas affichée dans l'interface utilisateur de Rancher.

ifeval::["{product}" == "fleet"]
Vous trouverez plus d'informations dans la documentation de Rancher : https://ranchermanager.docs.rancher.com/how-to-guides/advanced-user-guides/enable-experimental-features/continuous-delivery.
endif::[]

ifeval::["{product}" == "continuous-delivery"]
Vous trouverez plus d'informations dans la documentation de Rancher : https://documentation.suse.com/cloudnative/rancher-manager/latest/en/rancher-admin/experimental-features/continuous-delivery.html.
endif::[]