= v0.13.0
:revdate: 2025-07-23
:page-revdate: {revdate}
:page-date: 2025-07-23 15:09:14 +0000 UTC

*发布于 2025-07-23 15:09:14 +0000 UTC，作者：`github-actions[bot]` 。*

== 说明

== 显著变化

* 现在已全面支持 HelmOps 和 OCI 存储，不再是试验性的。
* 提高构建图像的可追溯性。
* 更准确、更轻量级的资源状态更新。

== 新增内容

* {product_name} 支持新的用户驱动捆绑扫描方法，具有更大的灵活性。仍支持以前的扫描方法。参见 @0xavi0 提供的xref:explanations/gitrepo-content.adoc#_alternative_scan_explicitly_defined_by_the_user[文档]，PRhttps://github.com/rancher/fleet/pull/3480[] #3480。
* 使用 SSH 指向 Git 仓库时，{product_name} 默认检查主机密钥，拒绝未知主机的连接尝试xref:/how-tos-for-users/gitrepo-add.adoc[已知主机]由https://github.com/weyfonk[PR#3523] @weyfonk 在link:https://github.com/rancher/fleet/issues/3523[].
* 控制器和代理的副本数量现在都可以配置。参见xref:how-tos-for-operators/installation.adoc#_controller_and_agent_replicas[文档]。
  (供稿：@p-se，公关https://github.com/rancher/fleet/pull/3457[] #3457)
* {product_name} 现在可以为每个 GitRepo 使用单独的 webhook 秘码。参见xref:how-tos-for-users/webhook.adoc#option-2-configure-secret[文档]。
  (供稿：@0xavi0，公关https://github.com/rancher/fleet/pull/3490[] #3490）
* {product_name} 图表现在支持额外的标签和注释，这些标签和注释会传播到控制器部署中。
  (由 @0xavi0 和 @p-se 提供，PR：https://github.com/rancher/fleet/pull/3531[]#3531 和https://github.com/rancher/fleet/pull/3664[] #3664)
* 代理领导选举现在可以配置。请参见https://github.com/rancher/fleet/blob/main/charts/fleet/values.yaml#L135-L138[示例]。
  (由 @p-se 供稿，公关https://github.com/rancher/fleet/pull/3463[] #3463)
* 旧服务帐户迁移已删除。(供稿：@weyfonk，公关https://github.com/rancher/fleet/pull/3601[] #3601）
* {product_name} 不再计算捆绑状态中的资源键。(由 @manno 供稿，公关https://github.com/rancher/fleet/pull/3681[] #3681)
* {product_name} 添加了新的 GitJob 指标。参见xref:how-tos-for-users/observability.adoc#_metrics[文档]。
  (供稿：@p-se，公关https://github.com/rancher/fleet/pull/3649[] #3649)
* 代理现在可以使用标签跳过群集。(由 @manno 供稿，公关https://github.com/rancher/fleet/pull/3744[] #3744)

=== HelmOps

HelmOps 不再是试验性的。现在支持`HelmOp` 资源（由`HelmApp` 更名而来）：

* 轮询 Helm 资源库
* 语义版本限制（见https://github.com/rancher/fleet/issues/3862[这一已知问题）] OCI 图表的
* 防止 GitOps 和 HelmOps 捆绑包之间的捆绑包命名冲突
* 以严格的 TLS 模式安装 Helm 图表

指标和群集状态现在包括 HelmOps 数据。更多信息，请参阅xref:how-tos-for-users/helm-ops.adoc[{product_name} 文档]。

=== OCI 存储

OCI 存储不再是试验性的，默认情况下已启用，但捆绑包默认情况下不会使用它。在安装{product_name} 时，仍可通过在`extraEnv` 中设置`OCI_STORAGE=false` 来禁用它。

它还支持尽力收集垃圾，并改进了 OCI 存储中所用机密的可追溯性。这包括标注{product_name} 克隆到下游群集的秘密，以及在删除 OCI 工件导致错误时生成事件。

详情请参见xref:how-tos-for-users/oci-storage.adoc[{product_name} 文档]。

=== 改进可追溯性

{product_name} 现在可以证明 Docker 清单的出处。
(由 @thardeck 修补，PRhttps://github.com/rancher/fleet/pull/3846[] #3846)

== 错误修复

状态更新和生命周期处理得到了重大改进：

* 现在，当多个捆绑包尚未准备就绪时，GitRepo 状态会更加稳定。
  (供稿：@rbreddy，公关https://github.com/rancher/fleet/pull/3485[] #3485）
* 优化了 GitRepo 状态更新。
  (PR https://github.com/rancher/fleet/pull/3604[#3604])
* 现在，GitRepo 对账会延迟更新，以提高快速变更时的性能。
  (PR https://github.com/rancher/fleet/pull/3558[#3558])
* 优化了 BundleDeployment 状态更新。
  (PR https://github.com/rancher/fleet/pull/3887[#3887])
* 漂移检测不再更新空差异的资源。
  (PR https://github.com/rancher/fleet/pull/3555[#3555])
* {product_name} 使用最新的 Wrangler 准备状态检测改进功能。
  (PR https://github.com/rancher/fleet/pull/3853[#3853])
* 下游代理再次向上游正确报告状态。
  (PR https://github.com/rancher/fleet/pull/3702[#3702])

=== 生命周期改进

* 集群事件过滤器可减少不必要的捆绑部署创建。
  (PR https://github.com/rancher/fleet/pull/3796[#3796])
* {product_name} 现在会删除过时的捆绑部署：
** 不再是目标。
** GitRepo 或捆绑目标已更改。
  (PRshttps://github.com/rancher/fleet/pull/3509[] #3509 和https://github.com/rancher/fleet/pull/3438[] #3438)

=== CLI 改进

* {product_name} CLI 现在能在 git 作业中提供更清晰的错误信息。
  (PR https://github.com/rancher/fleet/pull/3559[#3559])
* CLI 使用`controller-runtime` 客户端。
  (PR https://github.com/rancher/fleet/pull/3670[#3670])

=== 配置改进

* 配置更新现在可以有选择地触发群集导入：
** 仅当相关字段发生变化时。
** 仅当存在有效的`apiServerURL` 时。
  (PRshttps://github.com/rancher/fleet/pull/3551[] #3551 和https://github.com/rancher/fleet/pull/3837[] #3837)
* 修正了`options.Helm`.NET Framework 4.0 引起的恐慌。
  (PR https://github.com/rancher/fleet/pull/3567[#3567])
* 不再允许使用空仓库 URL 创建 GitRepo。
  (PR https://github.com/rancher/fleet/pull/3582[#3582])
* 现在会省略 BundleDeployments 和 HelmOps 中的空忽略选项。
  (PR https://github.com/rancher/fleet/pull/3842[#3842])

=== 其他改进

* 更多图表下载失败的信息错误。
  (PR https://github.com/rancher/fleet/pull/3593[#3593])
* Helm 图表下载的 SSH 密钥验证再次正常工作。
  (PR https://github.com/rancher/fleet/pull/3670[#3670])
