= Utilización de la exploración de imágenes para actualizar referencias de imágenes de contenedores
:revdate: 2025-04-30
:page-revdate: {revdate}

El escaneo de imágenes en fleet le permite escanear su repositorio de imágenes, obtener la imagen deseada y actualizar su repositorio git, sin necesidad de actualizar manualmente sus manifiestos.

[CAUTION]
====

Esta función se considera experimental.
====


Vaya a `fleet.yaml` y añada la siguiente sección.

[,yaml]
----
imageScans:
# specify the policy to retrieve images, can be semver or alphabetical order
- policy:
    # if range is specified, it will take the latest image according to semver order in the range
    # for more details on how to use semver, see https://github.com/Masterminds/semver
    semver:
      range: "*"
    # can use ascending or descending order
    alphabetical:
      order: asc

  # specify images to scan
  image: "your.registry.com/repo/image"

  # Specify the tag name, it has to be unique in the same bundle
  tagName: test-scan

  # specify secret to pull image if in private registry
  secretRef:
    name: dockerhub-secret

  # Specify the scan interval
  interval: 5m
----

[IMPORTANT]
====

Puedes crear múltiples escaneos de imagen en fleet.yaml.
====


[NOTE]
====

Semver ignorará las versiones anteriores al lanzamiento (por ejemplo, 0.0.1-10) a menos que se utilice explícitamente una versión anterior al lanzamiento en la definición del rango.
Por ejemplo, el rango "*" ignorará las versiones anteriores, mientras que ">= 0.0.1-10" las tendrá en cuenta.
====


Vaya a sus archivos de manifiesto y actualice el campo que desea sustituir. Por ejemplo:

[,yaml]
----
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-slave
spec:
  selector:
    matchLabels:
      app: redis
      role: slave
      tier: backend
  replicas: 2
  template:
    metadata:
      labels:
        app: redis
        role: slave
        tier: backend
    spec:
      containers:
      - name: slave
        image: <image>:<tag> # {"$imagescan": "test-scan"}
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 6379
----

[NOTE]
====

Existen múltiples formas de tagName a las que puede hacer referencia. Por ejemplo

`{"$imagescan": "test-scan"}`: Utilizar el nombre completo de la imagen (foo/bar:tag)

`{"$imagescan": "test-scan:name"}`: Utilizar sólo nombre de imagen sin etiqueta(foo/bar)

`{"$imagescan": "test-scan:tag"}`: Utilice sólo la etiqueta de imagen

`{"$imagescan": "test-scan:digest"}`: Utilice el nombre completo de la imagen con digest(foo/bar:tag@sha256...)
====


Crea un GitRepo que incluya tu fleet.yaml

[,yaml]
----
kind: GitRepo
apiVersion: fleet.cattle.io/v1alpha1
metadata:
  name: my-repo
  namespace: fleet-local
spec:
  # change this to be your own repo
  repo: https://github.com/rancher/fleet-examples
  # define how long it will sync all the images and decide to apply change
  imageScanInterval: 5m
  # user must properly provide a secret that have write access to git repository
  clientSecretName: secret
  # specify the commit pattern
  imageScanCommit:
    authorName: foo
    authorEmail: foo@bar.com
    messageTemplate: "update image"
----

Pruebe a introducir una nueva etiqueta de imagen, por ejemplo, `<image>:<new-tag>`. Espere un momento y debería haber un nuevo commit en su repositorio git para cambiar la etiqueta en deployment.yaml.
Una vez realizado el cambio en el repositorio git, fleet leerá el cambio y lo desplegará en tu cluster.
